services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk17
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    #  - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net

  jenkins_agent:
    build: .
    privileged: true
    user: root
    container_name: agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "22:22"
    networks:
      - net

networks:
  net:

volumes:
  jenkins_home:
  agent1-workdir: